[package]
name = "check_useless_chaining"
version = "0.1.0"
authors = ["chao450 <lin.chao.xz@gmail.com>"]

[dependencies.oak_runtime]
path = "oak/runtime"
version = "0.5.5"

[dependencies.oak]
path = "oak"
version = "0.5.6"
